
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: futbol-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - redis
      - ollama
    ports:
      - "8081:8081"
    environment:
      LLM_BASE_URL: http://ollama:11434
      LLM_MODEL: llama3.2:3b 

  web:
    image: nginx:alpine
    container_name: futbol-nginx
    depends_on:
      - app
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: mysql:8.0
    container_name: futbol-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: futbol
      MYSQL_USER: futbol
      MYSQL_PASSWORD: futbol
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: futbol-redis
    ports:
      - "6379:6379"
        
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: futbol-phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      # Si quieres permitir definir otros servidores manualmente en la UI:
      # PMA_ARBITRARY: 1
    ports:
      - "8080:80"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"   # opcional: per provar des del teu PC
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  db-data:
  ollama_data:

